"""
Two agents (Alice and Bob) talk to each other for 10 rounds via the message app.
Each agent's replies are generated by claude -p.

Usage:
    python example/agent_chat.py
"""

import re
import subprocess
import tempfile
import threading
import time

import requests

from inact import Inact, mount_message, mount_register

BASE_URL = "http://127.0.0.1:17432"


def start_server():
    db = tempfile.mktemp(suffix=".db")
    app = Inact("agent-chat")
    mount_register(app, "/agents", db)
    mount_message(app, "/msg", db)
    t = threading.Thread(
        target=lambda: app.run(port=17432, debug=False, use_reloader=False),
        daemon=True,
    )
    t.start()
    time.sleep(0.8)
    return db


def register(name: str) -> tuple[int, str]:
    r = requests.post(f"{BASE_URL}/agents/", json={"name": name}).text
    agent_id = int(re.search(r"id\s+=\s+(\d+)", r).group(1))
    api_key = re.search(r'api_key\s+=\s+"([^"]+)"', r).group(1)
    return agent_id, api_key


def send(from_id: int, to_id: int, body: str):
    requests.post(f"{BASE_URL}/msg/send", json={"from": str(from_id), "to": str(to_id), "body": body})


def latest_message(agent_id: int) -> str | None:
    inbox = requests.get(f"{BASE_URL}/msg/inbox", headers={"X-Agent-Id": str(agent_id)}).text
    urls = re.findall(r'url\s+=\s+"([^"]+)"', inbox)
    if not urls:
        return None
    detail = requests.get(BASE_URL + urls[0]).text
    m = re.search(r"---\n\n(.+)", detail, re.DOTALL)
    return m.group(1).strip() if m else None


def think(name: str, other: str, received: str) -> str:
    prompt = (
        f"You are {name}, an AI agent. "
        f"You are having a philosophical conversation with {other}. "
        f"{other} just said: \"{received}\"\n"
        f"Reply thoughtfully in 2-3 sentences. Be curious and engaging."
    )
    result = subprocess.run(["claude", "-p", prompt], capture_output=True, text=True, timeout=60)
    return result.stdout.strip()


def main():
    print("Starting server...")
    db = start_server()

    alice_id, _ = register("Alice")
    bob_id, _ = register("Bob")
    print(f"Alice (id={alice_id}), Bob (id={bob_id})\n")

    # Alice opens the conversation
    opener_prompt = (
        "You are Alice, an AI agent. Start a philosophical conversation with "
        "another AI agent named Bob. Write 2-3 sentences to kick things off."
    )
    opener = subprocess.run(
        ["claude", "-p", opener_prompt], capture_output=True, text=True, timeout=60
    ).stdout.strip()
    send(alice_id, bob_id, opener)
    print(f"Alice: {opener}\n")

    # Alternate for 10 rounds: Bob replies, then Alice, etc.
    speakers = [(bob_id, "Bob", alice_id, "Alice"), (alice_id, "Alice", bob_id, "Bob")]
    for round_num in range(10):
        speaker_id, speaker_name, listener_id, listener_name = speakers[round_num % 2]
        received = latest_message(speaker_id)
        if not received:
            print(f"[round {round_num + 1}] {speaker_name} has no new messages, skipping")
            continue
        reply = think(speaker_name, listener_name, received)
        send(speaker_id, listener_id, reply)
        print(f"[round {round_num + 1}] {speaker_name}: {reply}\n")

    print("--- conversation complete ---")
    import os; os.unlink(db)


if __name__ == "__main__":
    main()
